import { loadSettings, resetSettings, saveSettings } from "../shared/storage.js";
import { THEMES, applyTheme } from "../shared/themes.js";
import { debounce, downloadJson, getByPath, setByPath } from "../shared/utils.js";

const sections = [
  { id: "themes", label: "Themes", icon: "◈", description: "Choose a preset or craft your own palette." },
  { id: "appearance", label: "Appearance", icon: "✦", description: "Typography, shape, depth, and motion." },
  { id: "wallpaper", label: "Backgrounds", icon: "▧", description: "Persistent local images and gradients." },
  { id: "privacy", label: "Privacy", icon: "◉", description: "Local visual concealment and panic controls." },
  { id: "productivity", label: "Productivity", icon: "⌁", description: "Focus modes, compact layout, and navigation." },
  { id: "accessibility", label: "Accessibility", icon: "◎", description: "Contrast, scaling, palettes, and motion." },
  { id: "ai", label: "AI-ready panel", icon: "✧", description: "Configure the empty future assistant workspace." },
  { id: "shortcuts", label: "Shortcuts", icon: "⌨", description: "Edit keyboard commands used on WhatsApp Web." },
  { id: "local-data", label: "Local data", icon: "◇", description: "Chat folders, labels, tags, and notes stay on-device." }
];
let settings = await loadSettings(); let activeSection = "themes";
const content = document.querySelector("#settings-content"); const toast = document.querySelector("#toast"); const saveStatus = document.querySelector("#save-status");
const persist = debounce(async () => { saveStatus.textContent = "Saving…"; settings = await saveSettings(settings); saveStatus.textContent = "All changes saved locally"; }, 180);
function showToast(message) { toast.textContent = message; toast.classList.add("is-visible"); setTimeout(() => toast.classList.remove("is-visible"), 1600); }
function controlRow({ title, description, control, keywords = "" }) { return `<div class="control-row" data-search="${title} ${description} ${keywords}"><div><b>${title}</b><span>${description}</span></div>${control}</div>`; }
function toggle(path, title, description, keywords) { return controlRow({ title, description, keywords, control: `<label class="switch"><input type="checkbox" data-path="${path}" ${getByPath(settings, path) ? "checked" : ""}><i></i></label>` }); }
function slider(path, title, description, min, max, unit = "") { const value = getByPath(settings, path); return controlRow({ title, description, control: `<div class="slider"><input type="range" min="${min}" max="${max}" value="${value}" data-path="${path}" data-number><output>${value}${unit}</output></div>` }); }
function select(path, title, description, options) { const value = getByPath(settings, path); return controlRow({ title, description, control: `<select data-path="${path}">${options.map(([id, label]) => `<option value="${id}" ${id === value ? "selected" : ""}>${label}</option>`).join("")}</select>` }); }
function color(path, title, description) { const value = getByPath(settings, path); return controlRow({ title, description, control: `<label class="color-control"><input type="color" value="${value}" data-path="${path}"><span>${value}</span></label>` }); }
function group(title, body, intro = "") { return `<section class="settings-card"><header><h2>${title}</h2>${intro ? `<p>${intro}</p>` : ""}</header>${body}</section>`; }

function renderThemes() { return group("Theme gallery", `<div class="theme-grid">${Object.entries(THEMES).map(([id, theme]) => `<button class="theme-card ${settings.theme === id ? "is-active" : ""}" data-theme="${id}" data-search="${theme.label} ${theme.description}"><div class="theme-swatch" style="--c1:${theme.colors.sidebar ?? settings.appearance.sidebar};--c2:${theme.colors.chatBackground ?? settings.appearance.chatBackground};--c3:${theme.colors.accent ?? settings.appearance.accent};--c4:${theme.colors.outgoingBubble ?? settings.appearance.outgoingBubble}"><i></i><i></i><i></i><i></i></div><b>${theme.label}</b><span>${theme.description}</span></button>`).join("")}</div>`, "Preset changes remain fully editable.") + group("Custom palette", [color("appearance.accent", "Accent color", "Highlights, focus rings, and active states."), color("appearance.sidebar", "Sidebar color", "Background for chat navigation."), color("appearance.chatBackground", "Chat background", "Base conversation canvas color."), color("appearance.header", "Header color", "Top bars and composer surfaces."), color("appearance.outgoingBubble", "Outgoing messages", "Your local outgoing bubble color."), color("appearance.incomingBubble", "Incoming messages", "Incoming bubble surface color.")].join("")); }
function renderAppearance() { return group("Typography", select("appearance.fontFamily", "Font family", "Choose a readable local font stack.", [["system","System"],["inter","Inter"],["rounded","Rounded"],["serif","Serif"],["mono","Monospace"]]) + slider("appearance.fontSize", "Base font size", "Scale primary WhatsApp interface text.", 12, 22, "px") + slider("accessibility.fontScale", "Global font scaling", "Additional accessibility scaling.", 80, 140, "%")) + group("Shape and depth", slider("appearance.radius", "Border radius", "Round panels and message bubbles.", 0, 28, "px") + select("appearance.bubbleStyle", "Bubble style", "Choose the message silhouette.", [["rounded","Rounded"],["pill","Pill"],["square","Square"]]) + toggle("appearance.shadows", "Shadows", "Add subtle depth to message surfaces.") + toggle("appearance.transparency", "Transparency", "Use translucent panels with backdrop blur.") + slider("appearance.opacity", "Panel opacity", "Transparency level for glass surfaces.", 45, 100, "%") + slider("appearance.blur", "Glass blur", "Backdrop blur intensity.", 0, 40, "px")) + group("Motion and density", slider("appearance.animationSpeed", "Animation speed", "Duration of local transitions.", 0, 500, "ms") + toggle("appearance.compact", "Compact mode", "Reduce row and message spacing.")); }
function renderWallpaper() { return group("Wallpaper source", select("wallpaper.mode", "Background mode", "Use the theme color, a gradient, or local image.", [["none","Theme background"],["gradient","Gradient"],["image","Local image"]]) + controlRow({ title: "Local wallpaper", description: "Stored only in Chrome local storage and restored after refresh.", control: `<label class="file-button">Choose image<input id="wallpaper-file" type="file" accept="image/*" hidden></label>` }) + controlRow({ title: "Gradient", description: "Any valid CSS gradient value.", control: `<input class="text-input wide" data-path="wallpaper.gradient" value="${settings.wallpaper.gradient}">` }) + toggle("wallpaper.animated", "Animated gradient", "Slowly move gradient backgrounds.")) + group("Wallpaper treatment", slider("wallpaper.blur", "Wallpaper blur", "Soften image detail behind messages.", 0, 24, "px") + slider("wallpaper.dim", "Wallpaper dim", "Dark overlay for message readability.", 0, 80, "%") + slider("wallpaper.brightness", "Brightness", "Adjust local wallpaper luminance.", 40, 160, "%") + select("wallpaper.size", "Scale", "Control wallpaper sizing.", [["cover","Cover"],["contain","Contain"],["auto","Original size"]]) + select("wallpaper.repeat", "Repeat", "Tile smaller wallpapers if desired.", [["no-repeat","No repeat"],["repeat","Repeat"],["repeat-x","Horizontal"],["repeat-y","Vertical"]]) + select("wallpaper.position", "Position", "Anchor the wallpaper in the chat.", [["center","Center"],["top","Top"],["bottom","Bottom"],["left","Left"],["right","Right"]])); }
function renderPrivacy() { return group("Visual privacy", toggle("privacy.blurChatList", "Blur chat list", "Blur the entire left conversation list.") + toggle("privacy.blurNames", "Blur chat names", "Conceal names until reveal.") + toggle("privacy.blurPreviews", "Blur message previews", "Hide sidebar snippets locally.") + toggle("privacy.blurAvatars", "Blur profile pictures", "Conceal contact and group avatars.") + toggle("privacy.blurConversation", "Blur conversation", "Blur the active chat content.") + toggle("privacy.blurMedia", "Blur media previews", "Conceal images and video thumbnails.") + select("privacy.revealMode", "Reveal behavior", "Choose hover or hold-shortcut reveal.", [["hover","Reveal on hover"],["shortcut","Reveal with shortcut"]])) + group("Emergency controls", toggle("privacy.hideConversation", "One-click hide content", "Hide the conversation message area entirely.") + toggle("privacy.hideOnline", "Hide online indicator", "Visually conceal online status text only.") + toggle("privacy.hideTyping", "Hide typing indicator", "Visually conceal typing status text only.") + toggle("privacy.panicMode", "Panic mode", "Blur and darken the complete WhatsApp interface.")); }
function renderProductivity() { return group("Workspace modes", toggle("productivity.sidebarCollapsed", "Collapsible sidebar", "Reduce the sidebar to an avatar rail.") + toggle("appearance.compact", "Compact mode", "Show more chats and messages at once.") + toggle("productivity.focusMode", "Focus mode", "Dim the sidebar until it is needed.") + toggle("productivity.zenMode", "Zen mode", "Hide navigation, header, and composer.") + toggle("productivity.readingMode", "Distraction-free reading", "Center conversation content at a comfortable width.")) + group("Quick navigation", controlRow({ title: "Command palette", description: "Search currently visible chats without automation.", control: `<kbd>${settings.shortcuts.quickNav}</kbd>` }) + controlRow({ title: "Recent chats", description: "The architecture reserves local metadata for recent chat shortcuts.", control: `<span class="badge">Local-ready</span>` })); }
function renderAccessibility() { return group("Inclusive display", toggle("accessibility.highContrast", "High contrast", "Increase text and boundary contrast.") + select("accessibility.colorBlindPalette", "Color-blind palette", "Use safer accent and message colors.", [["none","Default"],["deuteranopia","Deuteranopia"],["protanopia","Protanopia"],["tritanopia","Tritanopia"]]) + slider("accessibility.fontScale", "Font scaling", "Scale interface typography without zooming Chrome.", 80, 140, "%") + toggle("accessibility.reducedMotion", "Reduced motion", "Disable nonessential transitions and animations.") + toggle("accessibility.keyboardFocus", "Visible keyboard focus", "Keep strong focus indicators for navigation.")); }
function renderAi() { return group("Groq AI", toggle("aiPanel.enabled", "Show the AI button", "Adds an AI button to WhatsApp Web.") + toggle("aiPanel.open", "Open AI when WhatsApp starts", "Keep the AI box open on the right.") + toggle("aiPanel.minimized", "Start as a small bar", "Show only the title until you open it.") + slider("aiPanel.width", "AI box width", "Make the AI box wider or narrower.", 280, 640, "px") + controlRow({ title: "Groq API key", description: "Paste your real Groq key here. It normally starts with gsk_.", control: `<div class="key-control"><input id="groq-api-key" class="text-input wide" type="password" autocomplete="off" placeholder="gsk_..."><button id="save-groq-key" class="secondary">Save & test</button><button id="clear-groq-key" class="secondary">Remove</button></div>` }), "The AI only sends text you put into its box."); }
function renderShortcuts() { return group("Keyboard shortcut editor", Object.entries(settings.shortcuts).map(([key, value]) => controlRow({ title: ({ panic:"Panic mode", reveal:"Temporary reveal", focus:"Focus mode", zen:"Zen mode", sidebar:"Collapse sidebar", aiPanel:"Assistant panel", quickNav:"Quick navigation" })[key], description: "Click and type a shortcut combination.", control: `<input class="shortcut-input" data-shortcut="${key}" value="${value}" readonly>` })).join(""), "Shortcuts are handled only while WhatsApp Web is active."); }
function renderLocalData() { return group("Local organization", controlRow({ title: "Favorite chats", description: "Data model ready for locally favorited visible chats.", control: `<span class="badge">${settings.productivity.favorites.length} saved</span>` }) + controlRow({ title: "Additional local pins", description: "Reserved local ordering without modifying WhatsApp pins.", control: `<span class="badge">${settings.productivity.localPins.length} saved</span>` }) + controlRow({ title: "Chat folders", description: "Local folder metadata stored in Chrome storage.", control: `<span class="badge">${settings.productivity.folders.length} folders</span>` }) + controlRow({ title: "Labels and color tags", description: "Local-only metadata architecture is included.", control: `<span class="badge">Ready</span>` }) + controlRow({ title: "Notes attached to chats", description: "Notes never leave this browser or alter conversations.", control: `<span class="badge safe">On-device</span>` }), "WhatsApp's current UI does not expose a stable public chat identifier, so metadata is safely reserved rather than attached heuristically."); }
const renderers = { themes: renderThemes, appearance: renderAppearance, wallpaper: renderWallpaper, privacy: renderPrivacy, productivity: renderProductivity, accessibility: renderAccessibility, ai: renderAi, shortcuts: renderShortcuts, "local-data": renderLocalData };

function renderNav() { document.querySelector("#nav").innerHTML = sections.map((section) => `<button data-section="${section.id}" class="${section.id === activeSection ? "is-active" : ""}"><span>${section.icon}</span>${section.label}</button>`).join(""); document.querySelectorAll("[data-section]").forEach((button) => button.addEventListener("click", () => { activeSection = button.dataset.section; render(); })); }
function bindControls() {
  content.querySelectorAll("[data-path]").forEach((element) => { const handler = () => { let value = element.type === "checkbox" ? element.checked : element.dataset.number !== undefined ? Number(element.value) : element.value; setByPath(settings, element.dataset.path, value); if (element.type === "color") { settings.theme = "custom"; element.nextElementSibling.textContent = value; } element.parentElement.querySelector("output") && (element.parentElement.querySelector("output").textContent = `${value}${unitFor(element.dataset.path)}`); updatePreview(); persist(); }; element.addEventListener(element.type === "range" || element.type === "color" ? "input" : "change", handler); });
  content.querySelectorAll("[data-theme]").forEach((button) => button.addEventListener("click", () => { settings = applyTheme(settings, button.dataset.theme); render(); persist(); showToast(`${THEMES[button.dataset.theme].label} applied`); }));
  content.querySelector("#wallpaper-file")?.addEventListener("change", async (event) => { const file = event.target.files[0]; if (!file) return; if (file.size > 8 * 1024 * 1024) return showToast("Choose an image under 8 MB"); settings.wallpaper.dataUrl = await fileToDataUrl(file); settings.wallpaper.mode = "image"; render(); persist(); showToast("Wallpaper stored locally"); });
  content.querySelectorAll("[data-shortcut]").forEach((input) => input.addEventListener("keydown", (event) => { event.preventDefault(); if (["Shift","Alt","Control","Meta"].includes(event.key)) return; const parts = [event.ctrlKey && "Ctrl", event.altKey && "Alt", event.shiftKey && "Shift", event.metaKey && "Meta", event.key.length === 1 ? event.key.toUpperCase() : event.key].filter(Boolean); if (parts.length < 2) return showToast("Include at least one modifier key"); settings.shortcuts[input.dataset.shortcut] = parts.join("+"); input.value = parts.join("+"); persist(); }));
  content.querySelector("#save-groq-key")?.addEventListener("click", async () => { const key = content.querySelector("#groq-api-key").value.trim(); if (!key.startsWith("gsk_")) return showToast("Paste the actual API key, not the words API key"); await chrome.storage.local.set({ waCanvasGroqApiKey: key }); const response = await chrome.runtime.sendMessage({ type: "WAC_GROQ", action: "Reply with exactly: Connection successful", text: "Test" }); if (!response?.ok) return showToast(`Saved, but test failed: ${response?.error || "Unknown error"}`); content.querySelector("#groq-api-key").value = ""; showToast("Groq connected successfully"); });
  content.querySelector("#clear-groq-key")?.addEventListener("click", async () => { await chrome.storage.local.remove("waCanvasGroqApiKey"); content.querySelector("#groq-api-key").value = ""; showToast("Groq key removed"); });
  applySearch();
}
function unitFor(path) { return path.includes("opacity") || path.includes("brightness") || path.includes("dim") || path.includes("Scale") ? "%" : path.includes("radius") || path.includes("blur") || path.includes("fontSize") || path.includes("width") ? "px" : path.includes("Speed") ? "ms" : ""; }
function fileToDataUrl(file) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file); }); }
function render() { renderNav(); content.innerHTML = `<div class="section-heading"><span>${sections.find((item) => item.id === activeSection).icon}</span><div><h2>${sections.find((item) => item.id === activeSection).label}</h2><p>${sections.find((item) => item.id === activeSection).description}</p></div></div>${renderers[activeSection]()}`; document.querySelector("#master-enabled").checked = settings.enabled; bindControls(); updatePreview(); }
function updatePreview() { const preview = document.querySelector("#preview"); const a = settings.appearance; preview.style.cssText = `--p-accent:${a.accent};--p-sidebar:${a.sidebar};--p-chat:${a.chatBackground};--p-header:${a.header};--p-text:${a.text};--p-muted:${a.mutedText};--p-out:${a.outgoingBubble};--p-in:${a.incomingBubble};--p-radius:${a.radius}px;--p-size:${a.fontSize * settings.accessibility.fontScale / 100}px;--p-blur:${a.blur}px;--p-opacity:${a.opacity / 100};--p-speed:${a.animationSpeed}ms;`; preview.className = `preview ${a.transparency ? "is-glass" : ""} ${a.compact ? "is-compact" : ""} ${settings.accessibility.highContrast ? "is-contrast" : ""} ${settings.productivity.sidebarCollapsed ? "is-collapsed" : ""}`; const messages = preview.querySelector(".preview-messages"); const w = settings.wallpaper; messages.style.backgroundImage = w.mode === "image" && w.dataUrl ? `linear-gradient(rgba(0,0,0,${w.dim/100}),rgba(0,0,0,${w.dim/100})),url("${w.dataUrl}")` : w.mode === "gradient" ? w.gradient : "none"; messages.style.backgroundSize = w.size; messages.style.backgroundRepeat = w.repeat; messages.style.backgroundPosition = w.position; messages.style.filter = `brightness(${w.brightness}%)`; }
function applySearch() { const query = document.querySelector("#settings-search").value.trim().toLowerCase(); content.querySelectorAll("[data-search]").forEach((element) => element.hidden = query && !element.dataset.search.toLowerCase().includes(query)); }
document.querySelector("#settings-search").addEventListener("input", () => { const query = document.querySelector("#settings-search").value.trim(); if (query) { const match = sections.find((section) => section.label.toLowerCase().includes(query.toLowerCase())); if (match && activeSection !== match.id) { activeSection = match.id; render(); return; } } applySearch(); });
document.querySelector("#master-enabled").addEventListener("change", (event) => { settings.enabled = event.target.checked; persist(); showToast(settings.enabled ? "WA Canvas enabled" : "WA Canvas paused"); });
document.querySelector("#preview-motion").addEventListener("click", () => { const preview = document.querySelector("#preview"); preview.classList.remove("replay"); requestAnimationFrame(() => preview.classList.add("replay")); });
document.querySelector("#export-button").addEventListener("click", () => downloadJson(`wa-canvas-settings-${new Date().toISOString().slice(0,10)}.json`, settings));
document.querySelector("#import-button").addEventListener("click", () => document.querySelector("#import-file").click()); document.querySelector("#import-file").addEventListener("change", async (event) => { try { const imported = JSON.parse(await event.target.files[0].text()); settings = await saveSettings(imported); render(); showToast("Settings imported"); } catch { showToast("That settings file is not valid"); } });
document.querySelector("#reset-button").addEventListener("click", async () => { if (!confirm("Reset all WA Canvas settings and local wallpaper?")) return; settings = await resetSettings(); render(); showToast("Defaults restored"); });
document.querySelector("#open-whatsapp").addEventListener("click", () => chrome.tabs.create({ url: "https://web.whatsapp.com/" }));
render();
